
module.exports.USERID = "704873671356973106"
module.exports.SERVERID = "239493425131552778"
module.exports.WEATHER="/home/runner/gtfbot/data/gtfweather"
module.exports.TIME="/home/runner/gtfbot/data/gtftime"
module.exports.GTSCARS="/home/runner/gtfbot/data/gtsportcarlist"
module.exports.CARS="/home/runner/gtfbot/data/gtfcarlist"
module.exports.TRACKS="/home/runner/gtfbot/data/gtftracklist"
module.exports.PARTS="/home/runner/gtfbot/data/gtfpartlist"
module.exports.PAINTS="/home/runner/gtfbot/data/gtfpaintlist"

module.exports.PERF="/home/runner/gtfbot/functions/marketplace/f_perf"
module.exports.RACE="/home/runner/gtfbot/functions/races/f_races"
module.exports.LOBBY="/home/runner/gtfbot/functions/lobbies/f_lobby"
module.exports.SEASONAL="/home/runner/gtfbot/functions/races/f_seasonals"
module.exports.GTF="/home/runner/gtfbot/functions/f_gtf"
module.exports.COURSEMAKER="/home/runner/gtfbot/functions/coursemaker/f_course"

module.exports.LISTS="/home/runner/gtfbot/index"
module.exports.MAIN="/home/runner/gtfbot/index"
module.exports.EMBED="/home/runner/gtfbot/functions/misc/f_embeds"
module.exports.MARKETPLACE="/home/runner/gtfbot/functions/marketplace/f_marketplace"
module.exports.EXP="/home/runner/gtfbot/data/gtfexp"
module.exports.REPLAY="/home/runner/gtfbot/functions/replays/f_replay"
module.exports.EXTRA="/home/runner/gtfbot/functions/misc/f_extras"
